### ISSUE TITLE
Cant start 7.3 version QT error

### ISSUE THREAD

**Issue by darkdef7** [In-line/DoubleClickFix#3]
error happens : This application falid to start because it could not find or load the Qt platform plugin "windows".
![default](https://user-images.githubusercontent.com/42557456/44370759-42803f80-a4e4-11e8-8859-a052c71c45f5.JPG)

Please help to fix it.... I need this programe.....

**Comment by darkdef7** [comment]
![default](https://user-images.githubusercontent.com/42557456/44370750-35fbe700-a4e4-11e8-87f1-b9b3dc922912.JPG)

**Comment by In-line** [comment]
Will fix soon :)

**Comment by darkdef7** [comment]
Big Thanks!!! You save me!!!


>Вторник, 21 августа 2018, 9:36 +03:00 от Alik Aslanyan <notifications@github.com>:
>
>Will fix soon :)
>

**Comment by In-line** [comment]
I was kindy lazy.. But don't worry, I'll keep my promise)

**Comment by darkdef7** [comment]
I will wait for you as much as need! Big thanks for help!
Alik Aslanyan <notifications@github.com> 24 августа 2018 г. 0:56:51 написал:

**Comment by In-line** [comment]
Hi, friend! I published new version, nothing really important changed. I just disabled "Minimize on start" button, because it is not really working well with new Qt.

I hope I also solved your problem!

I didn't update this piece of the software for the while, because I don't use it for now.

https://github.com/In-line/DoubleClickFix/releases/tag/Beta0.7.4

**Comment by darkdef7** [comment]
Oh no, i need this function... I think you fix this version with working -m 
autostart...
Alik Aslanyan <notifications@github.com> 31 августа 2018 г. 0:44:15 написал:
